"""empty message

Revision ID: 6e7dd7a52539
Revises: 2037c268b1dc
Create Date: 2020-07-17 15:03:41.147771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e7dd7a52539'
down_revision = '2037c268b1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image', sa.String(length=150), nullable=True))
    op.drop_column('movie', 'poster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('poster', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'image')
    # ### end Alembic commands ###
